import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect, useState } from "react";
import axios from "axios";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const [loading, setLoading] = useState(false);
  const [subsList, setSubsList] = useState([]);

  const getData = async () => {
    // console.log("test");

    const { data } = await axios.get("/api/youtubePlaylist", {
      withCredentials: true,
    });
    // console.log(data);

    return data;
  };

  useEffect(() => {
    getData().then(
      (data) => console.log("data", data)
      /* setSubsList(
        data.map((sub: { id: any; snippet: { title: any } }) => ({
          id: sub.id,
          title: sub.snippet.title,
        }))
      ) */
    );
  }, []);

  // console.log("session", session?.user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {session && <h1>Hello {session.user?.name} </h1>}

      <div className={styles.description}>
        <h2>Track your personal progress</h2>
        <h3>Learn better and faster with a true learning companion</h3>
        <p>
          Load Youtube video courses from the{" "}
          <a href='/courses'>Courses Section</a> or directly from Youtube.
          <br />
          Add your selected Youtube videos in the Courses Section or Log in and
          add your courses in the courseyard Youtube playlist created.
        </p>
        <div className={styles["button-container"]}>
          {session ? (
            <a href='/signout'>Log Out</a>
          ) : (
            <a href='/signin'>Log In</a>
          )}
          <a href='/courses'>Start Learning</a>
        </div>
      </div>
    </div>
  );
};

export default Home;
